FROM node:8.12.0-alpine

# TODO change WORKDIR
WORKDIR /usr/src/back-end

# Install deps
RUN apk update && apk add python make gcc g++
RUN npm install -g nodemon knex jest eslint eslint-plugin-jest

COPY ./package* ./

RUN npm install

COPY . .

# Expose ports (for orchestrators and dynamic reverse proxies)
EXPOSE 5000
